name: car_collisions
version: 0.0.2
author: Dzenan Ridjanovic
description: A game with moving cars of different colors, whose objective is to move the red car without collisions.
homepage: http://ondart.me/
dependencies:
  browser: any
